title: Amir Technical Journal
email: amirsarebani1381@gmail.com
description: >-
  A personal technical journal where I document and reflect on things I read.
baseurl: ""
url: ""
linkedin_username: amirsarebani81
github_username: amirsarebani81
permalink: pretty

theme: minima
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
